### ISSUE TITLE
Resize images in the editor

### ISSUE THREAD

**Issue by October45** [digabi/rich-text-editor#133]
Pictures used to show a source for a solution always show up really big with no way of changing it except for downloading the HTML file and adjusting the size there with CSS.

**Comment by sluukkonen** [comment]
Could you provide an example? I think we [limit the maximum width of images](https://github.com/digabi/rich-text-editor/blob/master/public/rich-text-editor.css#L47) to the width of the editor component already.

**Comment by Flappo420** [comment]
I mean that inside the editor you would be able to resize the image like you would a web browser inside Windows, grab a corner or a side and drag it to the desired size. But unlike the web browser the image would keep it's aspect ratio, so that you only change either the width or height. We've all complained about it in class and we think that it would be a great feature if you find a way to accomplish it. Maybe just even setting the scale like "x0.75" if that's easier.

**Comment by sluukkonen** [comment]
Ah, I I think I understand you now.

So far our philosophy has been to embed screenshots without any resizing, so the teacher grading the exam sees the same thing as the student on their computer. It's quite tricky problem to solve, since the student doing the exam and the teacher grading it might have displays with wildly different resolutions and pixel densities, so a screenshot that looks good on one screen might be too small or too big on another. 

That's why we've taken a conservative approach so far and haven't tried to resize the screenshots. A screenshot that potentially looks too big to the teacher grading the exam has seemed like the lesser evil.
