### ISSUE TITLE
Dfrac changes to frac if edited

### ISSUE THREAD

**Issue by shnigi** [digabi/rich-text-editor#380]
Dfrac formula `\dfrac{\frac{1}{2}}{\dfrac{3}{4}}` changes to frac if edited `\frac{\frac{1}{2}}{\frac{3}{4}`
![dfrac](https://user-images.githubusercontent.com/4188125/136948778-fcfc213f-6e3e-45fc-bcbf-dfd39725dd14.png)
![frac](https://user-images.githubusercontent.com/4188125/136948791-c42d7ed6-f4be-412c-94b3-1e3246d71af2.png)

The formula changes from dfrac to frac when editing

**Comment by kunring** [comment]
This behaviour is caused by mathquill. If this is an issue, it should be moved to https://github.com/digabi/mathquill

However this is intended mathquill behaviour. The latex commands `\frac`, `\dfrac`, `\cfrac` and `\fraction` are all converted to the mathquill command \frac for the purposes of simplifying what mathquill displays the same.
