### ISSUE TITLE
 [BUG] Using the \degree or \deg breaks math boxes

### ISSUE THREAD

**Issue by antoKeinanen** [digabi/rich-text-editor#449]
### [BUG] Using the \degree or \deg breaks math boxes

**To Reproduce**
1. Go to website: https://math-demo.abitti.fi/ it also works on most other apps using rich-text-editor.
2. Create a new math box by clicking "lisää kaava" or by pressing Ctrl-E.
3. Write into the box \degree or \deg.
4. Press enter.
5. See the error.

**Expected behavior**
° will be added to the math box, like with \sqrt and not the red exclamation mark.

**Screenshots**
![image](https://user-images.githubusercontent.com/62938747/151840746-bc338545-0253-453d-8661-14cf20aebf21.png)

**Desktop (please complete the following information):**
 - OS: Debian 11 but it didn't work on my Windows 10 laptop
 - Browser: Firefox 91.5.0esr (64-bit)

**Additional context**
Nothing critical but very annoying.

**Comment by kunring** [comment]
Is this issue being disregarded as a mathjax issue? It seems like an Abitti feature request to me. Mouseless degree insertion is highly requested. Abitti's modified mathquill uses \deg in a way which is incompatible with the MathJax library. This issue is specifically about how Abitti sicked these libraries together.

Suggested solution:
Modify digabi/mathquill to insert the unicode degree character `°` when \deg or \degree is used. It's already done like this with the buttons of the editor.

**Comment by kunring** [comment]
Fix here https://github.com/digabi/mathquill/pull/11
